/*
* Generated file
*
* Generated from: yang module name: nicira-extension-provider-impl yang module local name: openflow-extension-nicira
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Jul 11 13:27:17 CEST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.openflow.extension.nicira.impl;
public class NiciraExtensionProviderModuleFactory extends org.opendaylight.controller.config.yang.openflow.extension.nicira.impl.AbstractNiciraExtensionProviderModuleFactory {

}
